### ISSUE TITLE
Сообщения об ошибках

### ISSUE THREAD

**Issue by LeKaitoW** [LeKaitoW/rdo-game5#1]
Необходимо обрабатывать:
- проверки на `!=null`
- `try`-`catch`

Например, https://github.com/LeKaitoW/rdo-game5/issues/14

**Comment by bogachev-pa** [comment]
В общем, я думаю, концепция такая: если получили эксепшн в ходе создания/открытия каких-то ресурсов, то в блоке `catch`, либо в блоке `finally` (если их и так надо закрыть после блока try`) их надо всех закрыть/удалить и вывести пользователю сообщение об ошибке (вероятно, просто диалоговое окно, где-нибудь должен быть сниппет на эту тему).
