### ISSUE TITLE
Где хранится состояние ?

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#10]
Перезапустил плагин. Кнопки на тех же местах, что при закрытии. Два вопроса
- где хранится состояние ?
- если ли история состояний ?

**Comment by LeKaitoW** [comment]
Состояние хранится в файле .json
Если открыть его текстовым редактором, то там как раз состояния кнопок и прочих элементов.

**Comment by aurusov** [comment]
Странно, я его открыл, там начальное состояние. А у меня на экране совсем другое. Ты когда состояние сбрасываешь в него ?

**Comment by LeKaitoW** [comment]
При нажатии Save.
https://github.com/LeKaitoW/rdo-game5/blob/release/current/rdo-game5/src/rdo/game5/Game5View.java#L577

**Comment by aurusov** [comment]
Выглядит правильным. Еще раз проверю.
