### ISSUE TITLE
Убрать лишнии кнопки

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#11]
Кнопки
- `Simulation`
- `Show graph`

кажутся лишними, потому что и без них можно запустить модель и открыть граф. После https://github.com/LeKaitoW/rdo-game5/issues/3 надо попробовать поработать без них и принять окончательное решение. Особых бонусов я не вижу.

**Comment by LeKaitoW** [comment]
- `Simulation` должна иметь пару отличий от обычного прогона: расстановка галочек для трассировки (пока не сделано, #9) и отображение графа по завершению прогона (тут пока нужен фикс, #5)
- `Show graph` действительно кажется необязательной. Делалась только как аналог кнопки из старых пятнашек.

**Comment by bogachev-pa** [comment]
В `Show graph` вижу одно преимущество: не надо раскрывать дерево сериализованных объектов, можно построить граф одним кликом. Кажется, открыть граф - частый юз-кейс в пятнашках и это может быть удобно.

**Comment by aurusov** [comment]
- Если `Simulation` будет ставить галочку, то оставим. А если будет отображать граф, то лучше назвать кнопку `Run experiment` или просто одним из этих слов.
- `Show graph` а мне больше нравится жмакать по трассировке, она уже на экране.

Я еще допускаю кнопку (скорее историю экспериментов), которая выведет и исходные данные и конечный результат
- расположение кнопок
- используемая эвристика
- кол-во вершин в графе
- стоимость решения
- граф

В общем все, что нужно для оформления лабы. Т.е. студент нахмакал 10-20 экспериментов, потом перемещается и отбирает самые интересные решения для отчета. Но истории у нас нет, можно оформить как задачу на будущее, на практику потянет.

**Comment by aurusov** [comment]
> Кажется, открыть граф - частый юз-кейс в пятнашках и это может быть удобно.

Не помню, когда открывал граф отдельной кнопкой на лекциях. Проще проверить исходные данные глазами и еще раз запустить прогон, а не думать на каких данных построен граф.

**Comment by LeKaitoW** [comment]
Upd:
Кнопка `Show graph` удалена.
Кнопка `Simulation` -> `Run experiment`
Заголовок `Simulation` -> `Experiment`
![screenshot from 2015-09-01 20 02 27](https://cloud.githubusercontent.com/assets/10632455/9610997/cbc9a7aa-50e5-11e5-910b-5ed9e3517fa0.png)

**Comment by aurusov** [comment]
Хорошо, ставь пул-реквест

**Comment by LeKaitoW** [comment]
Задача решена: LeKaitoW/rdo-game5#18
