### ISSUE TITLE
Поле Select heuristic

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#12]
- Переименовать в `Heuristic`, потому что и так понятно, что это выбор. Ты же не пишешь на каждой кнопе `Button`.
- Поле позволяет себя редактировать. Так и задумано ?

**Comment by LeKaitoW** [comment]
Редактирование поля - да, так и задумано, чтобы в нем писать название своей эвристики.

**Comment by aurusov** [comment]
Тогда фон элемента должен быть белым. Сейчас он выглядит как read-only.

**Comment by LeKaitoW** [comment]
Решение этой проблемы не закоммитить никак, кроме как добавить пару строчек в ридми.

Причина: баг в Марсе для GTK3
- http://www.jroller.com/andyl/entry/mars_on_linux
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=463733

Решение (добавить в ридми):
`For Eclipse Mars:`
`Run` > `Run Configurations` > `Eclipse Application` > Tab `Environment` > `New...` > `Name:` = `SWT_GTK3` > `Value:` = `0` > `OK` > `Apply` > `Run`

Строчки в ридми добавлять? Править в них ничего не нужно?

**Comment by bogachev-pa** [comment]
Под виндой под марсом все ок.

**Comment by LeKaitoW** [comment]
Тогда `For Eclipse Mars:` -> `For Eclipse Mars under Linux:`?

**Comment by bogachev-pa** [comment]
Да, например так. Возможно, стоит еще написать, зачем/в каком случае это надо сделать.

**Comment by aurusov** [comment]
Паша, смени картинку. Сколько можно просить/уговаривать ?

**Comment by aurusov** [comment]
Если это касается только Марса, то отдельно завел https://github.com/LeKaitoW/rdo-game5/issues/19

**Comment by aurusov** [comment]
Напиши
Для исправления `[ошибки](url)` в Eclipse Mars under Linux, надо ...

**Comment by bogachev-pa** [comment]
> Паша, смени картинку. Сколько можно просить/уговаривать ?

сменил

**Comment by aurusov** [comment]
О, другое дело, няшный бобёро-скорп

**Comment by LeKaitoW** [comment]
Кто? о_О

**Comment by aurusov** [comment]
Я так вижу (с)

**Comment by LeKaitoW** [comment]
Поискать, как прописать настройку в eclipse.ini.

**Comment by aurusov** [comment]
После добавления `SWT_GTK3 = 0` Марс стал работать как Луна.
![2015-09-05 15 29 50](https://cloud.githubusercontent.com/assets/5585202/9699217/1614cf60-53e3-11e5-82ba-b18057819427.png)
Но это в другой таске https://github.com/LeKaitoW/rdo-game5/issues/19
По это осталось
- https://github.com/LeKaitoW/rdo-game5/issues/12#issuecomment-137173214
- https://github.com/LeKaitoW/rdo-game5/issues/12#issuecomment-137949187
