### ISSUE TITLE
Своя эвристика

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#13]
Вбил свою функции в окошке `Heuristic code`

``` erlang
int fun()
{
    return 1;   
}
```

Как начать её использовать в качестве эвристики ?

**Comment by LeKaitoW** [comment]
Написать fun() в поле выбора эвристики. Скорее всего, я ещё не сделала листенер клавиш на это поле, не помню точно. Нужно сделать эдитор dirty (то есть поставить и убрать какую-нибудь галочку) и сохранить. 
Это последний недоделанный листенер.

**Comment by aurusov** [comment]
В общем я так и делал, не работает.

**Comment by aurusov** [comment]
Я так и делал, не работает.

**Comment by LeKaitoW** [comment]
Теперь всё должно работать.
