### ISSUE TITLE
Странная обработка ошибок

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#14]
Сделал поле `Select heuristic` пустым. Нажал на сохранить. Модель перестала компилиться, потому что вместо DPT вставилось `null`.

Повторить не могу, но получил что-то вида
![2015-08-29 22 41 58](https://cloud.githubusercontent.com/assets/5585202/9563977/2f9113f2-4e9f-11e5-99e8-b4e5c9850182.png)

**Comment by LeKaitoW** [comment]
Получается несколько другое - в модели появляется строчка evaluateBy();
Соответственно, появляется ошибка в файле .rao, которая не дает модели скомпилиться. Или ожидается, что каждую ошибку в модели надо обрабатывать и выбрасывать сообщение?
Странная задача, ведь в evaluateBy() может быть задано выражение, а как его проверять на валидность - не очень понятно.

**Comment by aurusov** [comment]
У меня никакой evaluateBy не появилось, было то, что на скрине. Она говорит об ошибке твоего генератора dpt imho.

**Comment by LeKaitoW** [comment]
Но от поля `Select heuristic` зависит эта одна-единственная строчка в модели. 
Ошибка была из-за другого.
https://github.com/LeKaitoW/rdo-game5/blob/release/current/rdo-game5/src/rdo/game5/ConfigurationParser.java#L17
К каждому `try`-`catch` планировала сделать обработчики, относила это к таске #1.

**Comment by aurusov** [comment]
Тогда забудь про поле `Select heuristic`. Попробуй понять, почему такое вообще может быть.

**Comment by aurusov** [comment]
Задача будет делаться в рамках https://github.com/LeKaitoW/rdo-game5/issues/1
