### ISSUE TITLE
Настроить цвет фона диалога пятнашек

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#19]
Сейчас под Луной цвет фона диалога и контролов отличается. Надо сделать единым, выбрать любой из двух текущих.
Под Марсом тоже какая-то проблема с фоном, но _может быть_ это другое, https://github.com/LeKaitoW/rdo-game5/issues/12.

**Comment by aurusov** [comment]
Оля, ты говорила, хотела поставить какой-то другой Эклипс (ни Марс и ни Луну). Какой ? Проявляется ли на нём эта ошибка ?

**Comment by LeKaitoW** [comment]
Я говорила про Неон, но ссылка оказалась всего лишь его анонсом. :(

Но есть 2 идеи:
1. Просто задать цвет фона, взяв цвет у эклипса. (У другого фона или ещё у кого-то. Чтобы под контролы подходил.)
2. Может быть `SWT.SHADOW_IN` у элементов `Group` обеспечивает такой цвет.

Завтра проверю второй вариант, если дело не в этом, буду пытаться задать цвет бэкграунда эдитора.

**Comment by LeKaitoW** [comment]
Тестировалось и на убунте (луна), и на винде (марс). Весь диалог теперь имеет белый фон.
![screenshot from 2015-10-12 15 09 41](https://cloud.githubusercontent.com/assets/10632455/10427616/b799649a-70f3-11e5-90e5-b63bf390bc79.png)

**Comment by aurusov** [comment]
Отлично, ставь пул-реквест.
