### ISSUE TITLE
Настроить кодировку проекта UTF-8

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#21]
По аналогии с https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.lib/.settings/org.eclipse.core.resources.prefs#L2
Тестировать под виндой, где системная кодировка cp1251 (главное, чтобы не utf-8)

**Comment by aurusov** [comment]
Задача блокирующая

**Comment by LeKaitoW** [comment]
Сделано по аналогии с рдо. Пулл реквест буду ставить, когда решу проблему с кодировкой самой лабы.

**Comment by aurusov** [comment]
Ого, можно писать две таски в коммите.
