### ISSUE TITLE
Настроить кодировку лабы UTF-8

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#22]
Вот это надо сделать как минимум https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.lib/.settings/org.eclipse.core.resources.prefs#L2.
Но кажется, что для диалога этого будет недостаточно. Тестировать под виндой, где системная кодировка cp1251 (главное, чтобы не utf-8)

**Comment by aurusov** [comment]
Если выставить кодировку проекта в utf-8, то шаблон начинает выглядеть по русски. Но вот эвристика косячит
![2015-09-06 16-09-03 rao - test game5 json - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/9704492/a6ff2344-54b1-11e5-9c4d-99baf5d4de98.png)
![2015-09-06 16-10-34 rao - test game5 rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/9704494/dbd4934c-54b1-11e5-99f2-09cb4172756b.png)

**Comment by aurusov** [comment]
Задача блокирующая

**Comment by LeKaitoW** [comment]
~~Пока ищу, как можно задать кодировку проекту при создании. Если не найду, то просто придется руками создавать папку `.settings` и файл в ней.~~
Задать кодировку проекту удалось, осталось только задать кодировку при парсинге JSON.
https://github.com/LeKaitoW/rdo-game5/blob/feature/encoding/rdo-game5/src/rdo/game5/Game5View.java#L104
