### ISSUE TITLE
Освободить графические ресурсы

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#24]
Цвет, [выделенный](https://github.com/LeKaitoW/rdo-game5/blob/release/current/rdo-game5/src/rdo/game5/TileButton.java#L38) через

``` java
new Color(...);
```

надо правильно удалять, чтобы графическая система отпустила этот ресурс. Думаю, что кроме цвета есть и другие объекты. Прошу
- скинуть ссылку на почитать как правильно работать с такими ресурсами
- в ней же или в другом месте - какие есть стандартные паттерны для их очистки
- проверить код на наличие таких мест и исправить

**Comment by bogachev-pa** [comment]
> скинуть ссылку на почитать как правильно работать с такими ресурсами

http://www.eclipse.org/articles/swt-design-2/swt-design-2.html

> в ней же или в другом месте - какие есть стандартные паттерны для их очистки

По ссылке под заголовком `When should you free?` расписано довольно подробно и с примерами.
