### ISSUE TITLE
Избавиться от ворнингов

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#4]
Налюдаю проблемы
- `Element 'action' is deprecated`
- `The extension point 'org.eclipse.ui.actionSets' is deprecated`

Вообще от слова `deprecated` надо избавляться как можно быстрее.

**Comment by bogachev-pa** [comment]
1. Вместо `actionsSets` и `action` стоит создавать меню через `menuContribution`, `menu` и `command`, как это делается в основном рдо: https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.ui/plugin.xml#L498, а в качестве обработчика вместо `Game5Action` нужно завести хэндлер команды.
2. Почему `wontfix`?

**Comment by aurusov** [comment]
Потому что это не бага, но исправить надо. Как бы ты назвал ?

**Comment by bogachev-pa** [comment]
Я использую для этого лэйбл `refactoring` обычно. Вообще, я думал `wontfix` означает, что проблема существует, но ее решение настолько трудоемко, что она фикситься не будет.

**Comment by aurusov** [comment]
Блин, использовал `wontfix` в смысле `wantfix` :)
Рефакторинг - может быть, но уж больно он для многих случаев подходит, т.е. значение размывается. Тогда это бага, чтобы не плодить статусы.

**Comment by LeKaitoW** [comment]
> Вместо actionsSets и action стоит создавать меню через menuContribution, menu и command, как это делается в основном рдо: https://github.com/aurusov/rdo-xtext/blob/release/current/ru.bmstu.rk9.rao.ui/plugin.xml#L498, а в качестве обработчика вместо Game5Action нужно завести хэндлер команды.

Сделано именно так, ворнингов нет.

**Comment by aurusov** [comment]
Давай добавим `visibleWhen`, как Паша написал.

**Comment by LeKaitoW** [comment]
Добавила условие.
Пулл реквест ставить?

**Comment by aurusov** [comment]
Ага

**Comment by LeKaitoW** [comment]
Задача решена: LeKaitoW/rdo-game5#20
