### ISSUE TITLE
Руководство пользователя

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#40]
Нужно простейшее руководство пользователя. [Оно](https://docs.google.com/document/d/1Wfuugpc5o9rxwHKkpurGC7bhdLCa_4nlA6GYYIP_1Ig/edit) для старой версии. Можно еще короче. Хоть в виде связанных скриншотов. Предлагаю один из форматов
- или Google Docs
- или чистый html с картинками и стилем
- или [github md](https://help.github.com/categories/writing-on-github/)

**Comment by LeKaitoW** [comment]
[Руководство пользователя](https://docs.google.com/document/d/1qygfLeVLfN1_i8bL3PsIxo3JwvFcCRQkPugY0_lApqs)
(Пока смотреть рано, ещё будут правки. В том числе и форматирование.)

**Comment by aurusov** [comment]
Как же ты мучаешься со скриншотами. Мне прям тебя жалко. Есть разные решения
- Под виндой Alt+PrintScreen.
- Под виндой https://yandex.ru/support/disk/screenshots.xml. Можно рисовать стрелочки, очень удобно. Я за этот вариант.
- Под линухами http://shutter-project.org/

**Comment by LeKaitoW** [comment]
UPD: Дописала [руководство](https://docs.google.com/document/d/1qygfLeVLfN1_i8bL3PsIxo3JwvFcCRQkPugY0_lApqs).

**Comment by aurusov** [comment]
Забрал себе.
