### ISSUE TITLE
Окно с раскладкой меняет свои размеры

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#41]
При переходе к следующему состоянию изменяется _размер_ диалога, кнопки уезжают.

![1_003](https://cloud.githubusercontent.com/assets/5585202/10710224/a27770c6-7a57-11e5-856e-cbf6beac9b7f.png)
![1_004](https://cloud.githubusercontent.com/assets/5585202/10710225/a52b1f98-7a57-11e5-9987-d62107e2443e.png)

**Comment by bogachev-pa** [comment]
Перенес в https://github.com/aurusov/rdo-xtext/issues/247, т.к. это дженерик код, а не код плагина.
