### ISSUE TITLE
Состояние поля под графом

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#43]
Граф закрывает состояние поля. Очень неудобно, когда окно графа на весь экран.

![1_010](https://cloud.githubusercontent.com/assets/5585202/10710254/100bd64e-7a59-11e5-8a28-ca9835b6efb2.png)

Хочется, чтобы поле было всегда сверху

![1_011](https://cloud.githubusercontent.com/assets/5585202/10710255/1a98ead4-7a59-11e5-9757-f6316fd4c380.png)

**Comment by bogachev-pa** [comment]
Перенес в https://github.com/aurusov/rdo-xtext/issues/246, т.к. это дженерик код, а не код плагина.
