### ISSUE TITLE
Добавить автосборку пятнашек на Дженкинс

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#44]
- [x] Сборка плагина пятнашек
- [x] Завести автосборку на Дженкинсе
- ~~Деплой плагина на ftp~~ Лучше деплоить сразу архив с РДО и Эклипсом. Но этоу другая [задача](https://github.com/aurusov/raox-deploy/issues/1).

**Comment by LeKaitoW** [comment]
Удалось сделать сборку, за исключением одного момента: у нас нет репозитария с джарниками рдо. Пока делаю с установкой джарников рдо в локальный репозитарий.

**Comment by aurusov** [comment]
Что значит удалось ? Настроен мавен ?

> Пока делаю с установкой джарников рдо в локальный репозитарий.

Мавен-репозитарий ? Собрать джарники РДО нажно на дженкинсе. Как положить в локальный мавен-репозитарий не знаю.

**Comment by LeKaitoW** [comment]
Для сборки необходим мавен-репозитарий с джарниками рдо (https://github.com/aurusov/rdo-xtext/issues/244), сейчас приходится делать mvn install в репозитории с рдо (после чего они попадают в локальный мавен-репозитарий и ссылку на них уже указывать не нужно) перед сборкой плагина пятнашек.

**Comment by aurusov** [comment]
Обновил шапку. Пока плохо понимаю что сделано и как оно работает. Давай завтра найдем время и обсудим.

**Comment by AlexChernov** [comment]
Установка зависимости от джарников

``` xml
<dependencies>
    <dependency>
        <groupId>ru.bmstu.rk9.rao</groupId>
        <artifactId>ru.bmstu.rk9.rao.ui</artifactId>
        <version>[2.9.0,)</version>
    </dependency>
  <dependency>
  ..
  </dependency>
</dependencies>
```

Мне кажется надо добавить в сборку в явном виде

**Comment by LeKaitoW** [comment]
Версии зависимостей в `build.properties` прописываются точь-в-точь как в `pom.xml`. Есть настройка минимальной/максимальной версии и опция `Inclusive/Exclusive`: https://github.com/LeKaitoW/rdo-game5/blob/feature/maven_build/rdo-game5/META-INF/MANIFEST.MF#L19

Использование гитового плагина на Дженкинсе для двух разных репозиториев (рдо и пятнашек) невозможно (http://stackoverflow.com/a/14844316).
Возможное решение:

```
export MAVEN_OPTS="-Xmx512M"
rm -rf rdo-xtext
rm -rf rdo-game5
git clone -b release/2.9 https://github.com/aurusov/rdo-xtext.git
git clone -b feature/maven_build https://github.com/LeKaitoW/rdo-game5.git
cd rdo-xtext
mvn initialize -N -Pset-git-version
mvn clean package
mvn install
cd ../rdo-game5
mvn initialize -N -Pset-git-version
mvn clean package
```

[Джарник пятнашек](http://rdo.rk9.bmstu.ru:81/job/raox-game5/ws/rdo-game5/assembly/target/plugins/)

**Comment by AlexChernov** [comment]
> Использование гитового плагина на Дженкинсе для двух разных репозиториев (рдо и пятнашек) невозможно (http://stackoverflow.com/a/14844316).

Ты делала это через плагин Git или через Multiple SCM? Как тут http://rdo.rk9.bmstu.ru:81/view/rdo_studio-AlexChernov/job/rdo-studio-AlexChernov-dev-gcc-debug/configure

**Comment by aurusov** [comment]
Оля больше не занимается этой задачей.

**Comment by aurusov** [comment]
```bash
export MAVEN_OPTS="-Xmx512M"
cd rdo-xtext
mvn initialize -N -Pset-git-version
mvn clean install
cd ../rdo-game5
mvn initialize -N -Pset-git-version
mvn clean package
```

**Comment by aurusov** [comment]
Сборка пятнашек на Дженкинсе требует сборки плагина, поэтому сценарий упростился

``` bash
export MAVEN_OPTS="-Xmx512M"
mvn initialize -N -Pset-git-version
mvn clean package
```

**Comment by aurusov** [comment]
Леша, отшлифуй результат.

**Comment by AlexChernov** [comment]
> Сборка пятнашек на Дженкинсе требует сборки плагина, поэтому сценарий упростился
> 
> ```
> export MAVEN_OPTS="-Xmx512M"
> mvn initialize -N -Pset-git-version
> mvn clean package
> ```

А как это будет работать без скачки и сборки плагина?

**Comment by aurusov** [comment]
Никак, написано же `требует сборки плагина`. Посмотри в свойствах сборки пятнашек. Там есть зависимость.

**Comment by AlexChernov** [comment]
Увидел. А пробовали чистить локальный репозиторий сборки http://rdo.rk9.bmstu.ru:81/job/raox-game5/ перед этим?

**Comment by aurusov** [comment]
Нет, а зачем ? Вдруг нам нужны старые версии. Переживаешь, что локальный мавен-репозитарий разрастётся ? Если ли в мавене команда очистки от старых версий ?

**Comment by AlexChernov** [comment]
Проверить, вдруг оно собирается, только потому что до этого делали `install` именно в этой сборке. Есть `mvn dependency:purge-local-repository -Dinclude=ru.bmstu.rk9.rao:ru.bmstu.rk9.rao`

**Comment by AlexChernov** [comment]
Запустил проверку

**Comment by AlexChernov** [comment]
Собралось, думаю можно закрывать
