### ISSUE TITLE
Постановка задачи на лабу

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#45]

**Comment by LeKaitoW** [comment]
[Постановка задачи](https://docs.google.com/document/d/1-27nJO6Rj8NjQtcvG4eWGfDlfqxsBgy7sRGhG1I8AFU/)

**Comment by LeKaitoW** [comment]
@aurusov 
Постановка задачи готова.

**Comment by aurusov** [comment]
Забрал к себе.
