### ISSUE TITLE
Пример отчета по лабе

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#46]

**Comment by LeKaitoW** [comment]
[Пример отчета](https://docs.google.com/document/d/1_sf-wEsZdLyXFdrG6z-Z01N_3iZj-86MvQlIMSvjEP4/)

**Comment by LeKaitoW** [comment]
UPD: Добавлена заливка, форматирование кода эвристики.

**Comment by aurusov** [comment]
Нужен доступ по записи

**Comment by aurusov** [comment]
Документ забрал себе. У себя можешь удалять. Таску закрываю.
