### ISSUE TITLE
Кнопка Simulation показывет старый граф

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#5]
Кнопка `Simulation` запускает симуляцию, но потом показывет старый граф. Приходится его закрывать и жмакать по кнопке `Show graph`.

**Comment by bogachev-pa** [comment]
Тут не хватает возможностей отложенных подписок.

Строить граф нужно при получении нотификации о `EXECUTION_COMPLETED`.
Работать это должно следующим образом:
1. В момент нажатии `Simulation`, регистрируется подписчик первого уровня на `SIMULATOR_INITIALIZED`, который в свою очередь регистрирует подписчика второго уровня на `EXECUTION_COMPLETED`, когда ему приходит оповещение.
2. После получения оповещения `EXECUTION_COMPLETED`, оба подписчика (и первого, и второго уровней) отписываются и строится граф.

Проблема в том, что текущая реализации отложенных подписок вызывает `fireChange()` на `SIMULATOR_INITIALIZED`-подписчика, если симулятор уже проиниализирован. Т.к. к моменту второго запуска, первый симулятор все еще проинициализирован, то `EXECUTION_COMPLETED` вызывается до выполнения команды запуска модели, в итоге строится старый граф.

Что касается решений проблемы, их два:
А. Накостылить в пятнашках собственные упрощенные отложенные подписки по схеме, описанной выше. `SimulationSubscriberManager` не использовать.
Б. Прокачать возможности подписок таким образом, чтобы решить эти проблемы, а именно:
- иметь возможность не оповещать подписчики первого уровня, если симулятор уже проинициализирован, а ждать его инициализации
- иметь возможность передавать подписчикам второго уровня кастомные флаги (`ONE_SHOT`, `IGNORE_ACCUMULATED`).

**Comment by aurusov** [comment]
Хм... Зачем что-то менять, если проблема понятна

> Т.к. к моменту второго запуска, первый симулятор все еще проинициализирован

Предлагаю исправить это место. Как так может быть, что _после_ завершения модели симулятор еще проинициализирован ?

**Comment by aurusov** [comment]
Паша, смени иконку. Мне неудобно общаться, в очередной раз приходится тратить время. Ты стесняешься что ли ?

**Comment by bogachev-pa** [comment]
> Предлагаю исправить это место. Как так может быть, что после завершения модели симулятор еще проинициализирован ?

Это означает, что данные о прогоне все еще доступны. Допустим, мы открыли какое-нибудь окошко (той же трассировки) после окончания прогона - нам нужно накормить его данными от этого прогона. После деинициализации симулятора данные потеряны.

Кейс в пятнашками другой - нам нужно забить на текущие данные вообще, т.к. мы собираемся запустить прогон заново.

> Паша, смени иконку. Мне неудобно общаться, в очередной раз приходится тратить время. Ты стесняешься что ли ?

Вы хотите, чтобы там была фотография или что? Вроде сейчас похожих аватарок ни у кого в тиме нет.

**Comment by aurusov** [comment]
> Вы хотите, чтобы там была фотография или что? Вроде сейчас похожих аватарок ни у кого в тиме нет.

Да, я хочу фотографию. Но если с этим проблемы, то картинку, которая отличается от стандартных.

**Comment by aurusov** [comment]
> Кейс в пятнашками другой - нам нужно забить на текущие данные вообще, т.к. мы собираемся запустить прогон заново.

Кейс в пятнашках самый стандартный. Видимо в стандартном ошибка. Я вижу так
- запуск
  - удаление старого симулятора, если был, все отписались
  - создание нового симулятора, все подписались
- моделирование закончилось, _об этом_ пришло уведомление, подписчики обработали результаты и трассировку
- запуск ...

**Comment by aurusov** [comment]
Задача не решена
