### ISSUE TITLE
Настроить свойства проекта пятнашек

### ISSUE THREAD

**Issue by AlexChernov** [LeKaitoW/rdo-game5#52]
https://github.com/aurusov/rdo-xtext/issues/212

**Comment by aurusov** [comment]
Это нормальное название ?
https://github.com/aurusov/raox-game5/blob/feature/maven_build/rdo-game5/META-INF/MANIFEST.MF#L5
Может его хотя бы через точку написать `rdo.game5` ?

**Comment by AlexChernov** [comment]
ru.bmstu.rk9.rao.game5 ?
 Или сразу ru.bmstu.rk9.raox.game5 ?

**Comment by bogachev-pa** [comment]
Я думаю, оно должно совпадать с именем пакета? По крайней мере в репозитории рдо это так.
Если переименовывать, то, наверное, вместе с пакетами в `ru.bmstu.rk9.rao.game5`?
Но это надо делать тогда нет других текущих пул-реквестов.

**Comment by aurusov** [comment]
> Если переименовывать, то, наверное, вместе с пакетами в `ru.bmstu.rk9.rao.game5`?
> Но это надо делать тогда нет других текущих пул-реквестов.

Согласен, потому что сейчас
![2015-11-01 22-23-22](https://cloud.githubusercontent.com/assets/5585202/10870867/35010d9a-80e7-11e5-8e1c-95ef45918c80.png)

**Comment by aurusov** [comment]
https://github.com/aurusov/raox-game5/issues/53
