### ISSUE TITLE
Первый эксперимент

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#55]
Проверялось под виндой, `workspace` удалялся. Плагины с Дженкинса (2.9.1 и 1.2.0). Проверил под двумя Марсами (1 и R). Поведение одинаковое.
- запускаю Экдипс, открывают перспективу Rao, создаю плагин c именем game5
- меняю с помощью мышки раскладку, сразу, без сохранения модели, жмакаю на `Run experiment`
- получаю пустой граф
- если еще раз нажать на `Run experiment`, то граф отображается

Под Mars-R словил ситуацию, когда при клике на вершину показывался текстовый отчет, но не выводилось поле.

**Comment by LeKaitoW** [comment]
Обнаружила этот баг пару дней назад.

Был исправлен здесь: https://github.com/aurusov/raox-game5/commit/8f3c8e5f113fdbdf04ebb477c45f409c573a9ed6#diff-c85a4f66f8aae66e920cb46687ab8223R468

Совсем забыла отписаться, извините.

**Comment by aurusov** [comment]
Тогда закрываем

**Comment by aurusov** [comment]
Исправлено тут https://github.com/aurusov/raox-game5/issues/2
