### ISSUE TITLE
Перемещение по графу вверх

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#58]
Для любой вершины, кроме рута, надо дать возможность ходить вверх.
![2015-11-05 11-56-28 _](https://cloud.githubusercontent.com/assets/5585202/10963877/9985c146-83b4-11e5-9a7f-45c7721fb10b.png)

**Comment by LeKaitoW** [comment]
Перенесено: https://github.com/aurusov/rdo-xtext/issues/268
