### ISSUE TITLE
Модель не запускается после исправления ошибки

### ISSUE THREAD

**Issue by AlexChernov** [LeKaitoW/rdo-game5#61]
Аналогично с #60 (скриншот оттуда), но в тексте ошибки вместе GraphPanel - GraphView
![signature](https://cloud.githubusercontent.com/assets/9211559/11014968/4ab75670-855c-11e5-8823-6b67ac4b094b.PNG)

**Comment by AlexChernov** [comment]
Возможно, ошибка происходит в результате попытки переопределения в окне для описания эвристики функции, уже заданной в тексте модели, например, `Расстояние_фишки_до_места()`, сейчас нет возможности проверить

**Comment by AlexChernov** [comment]
@Erm0chenkovNagibator666 воссоздал в #63 

> Я создал еще проект - написал `double checkar()  {return Math.sin(15.0);}` - работает!
> Поменял ей тип на `int` - получил ошибку как в первом скрине поста.
> Вернул `double`, еще раз нажал **Run experiment** и вышло это: 
> ![71](https://cloud.githubusercontent.com/assets/15702804/11094187/50fd86bc-889f-11e5-9133-a3078620e40e.png)

**Comment by bogachev-pa** [comment]
Дубликат этой таски: https://github.com/aurusov/raox-game5/issues/60
