### ISSUE TITLE
Модель не запускается после исправления ошибки

### ISSUE THREAD

**Issue by Erm0chenkovNagibator666-zz** [LeKaitoW/rdo-game5#63]
Меня попросил @AlexChernov запостить, как это было на лабе.

Я создал обычный новый проект **test1** через Rao Game5 plugin. В пространстве для создания эвристики плагина создал функцию:
`int testFunc()
{
    return -0.5;
}`

Запустил через кнопку **Run experiment** в плагине (эвристику в окне выбора не менял). Вышла вот такая ошибка при запуске:

![66](https://cloud.githubusercontent.com/assets/15702804/11092513/1facc92e-8895-11e5-8d0b-62bdb3585256.png)

При этом в файле с моделью (**game5.rao**) в самом конце появилась эта функция.
Если теперь исправить ошибку в фукнции **testFunc**, то код в **game5.rao** перезапишется, но на запуске возникнет ошибка: 
![68](https://cloud.githubusercontent.com/assets/15702804/11092583/8a84c2e2-8895-11e5-9533-93e04062f7b2.png)

Если проверить **game5.rao**, то там окажется вполне legit код:

![69](https://cloud.githubusercontent.com/assets/15702804/11092638/e959bb7e-8895-11e5-8edf-6f7626212698.png)

Насчет issue #61 Graph View у меня не получилось воссоздать.

**Comment by AlexChernov** [comment]
У тебя же не перезаписывалась модель? Ты еще хотел добавить синус или что-то такое?

**Comment by Erm0chenkovNagibator666-zz** [comment]
@AlexChernov я проверил сейчас с синусом. Написал в новом проекте в плагине double `checkar()
{
    return Math.sin(15.0);
}`   вроде должно быть правильно, по документации Java проверил правильно ли вызван Math.sin

При **Run experiment** выдает ошибку как в #60 
То есть ошибок в коде нет, но панель не запускает с синусом(хотя я даже не запускаю эту функцию как эвристику).

![70](https://cloud.githubusercontent.com/assets/15702804/11093453/63b57016-889b-11e5-87aa-aa651ae840b5.png)

**Comment by AlexChernov** [comment]
@Erm0chenkovNagibator666 Теперь исправь `return Math.sin(15.0);` на `return 0.5;` и проверь исправляется ли эта строчка в модели. Вроде у тебя такая проблема была изначально?

**Comment by Erm0chenkovNagibator666-zz** [comment]
@AlexChernov меняется. 
У меня сейчас вообще магия произошла. Я закрыл/открыл эклипс и теперь синус работает.

Я создал еще проект - написал `double checkar()  {return Math.sin(15.0);}` - работает!
Поменял ей тип на `int` - получил ошибку как в первом скрине поста.
Вернул `double`, еще раз нажал **Run experiment** и вышло это: 
![71](https://cloud.githubusercontent.com/assets/15702804/11094187/50fd86bc-889f-11e5-9133-a3078620e40e.png)

Че вообще происходит?

**Comment by bogachev-pa** [comment]
> Че вообще происходит? 

https://github.com/aurusov/raox-game5/issues/61

У тебя получилось "воссоздать".

**Comment by AlexChernov** [comment]
Хочется, чтобы ты воспроизвел именно ту ошибку, которая была на лабораторной работе, когда модель не перезаписывалась.

> по документации Java проверил правильно ли вызван Math.sin

Может у тебя получится вспомнить, как ты написал ее в первый раз на самой лабе? Да и вообще дальнейшие твои действия.

**Comment by bogachev-pa** [comment]
Ошибка, вызванная этой функцией:

```
int testFunc() { return -0.5; }
```

вполне логична.

Все, что дальше - дубликат этой таски: https://github.com/aurusov/raox-game5/issues/60
