### ISSUE TITLE
Нет иконки пятнашек в визарде

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#68]
![2015-12-05 23-28-48 new project](https://cloud.githubusercontent.com/assets/5585202/11610031/083ec03c-9ba8-11e5-90d1-49017060f49e.png)

**Comment by LeKaitoW** [comment]
Это даже не совсем баг.
Иконки в принципе нет. У диалога пятнашек иконки тоже нет.
Будем использовать старую, которая была в пятнашках @AlexChernov?

**Comment by aurusov** [comment]
У диалога можно не делать. Но в визарде смотрится странно.

**Comment by bogachev-pa** [comment]
Решено в этом коммите: https://github.com/aurusov/raox-game5/pull/74/commits/bf06a547ff9fdeee249ab9b848b332840e70a794
(не заметил, что есть такая таска, так что не отреференсил)

**Comment by aurusov** [comment]
Только это не иконка пятнашек

**Comment by bogachev-pa** [comment]
Ну, у нас нет отдельной иконки пятнашек. У нас и иконки нового рдо нет, если уж на то пошло, используем старую иконку.

**Comment by aurusov** [comment]
Есть от старых версий и для того и для другого. Даже несколько разных вариантов. Попробую заюзать для пятнашек и сравнить с текущей. Если понравится, то поставлю реквест.

**Comment by bogachev-pa** [comment]
Окей.

**Comment by aurusov** [comment]
Проблема осталась. Если запускать из dev-Эклипса, то иконка есть. Если из продового - нет.
