### ISSUE TITLE
Количество вершин графа

### ISSUE THREAD

**Issue by IChesnokov5** [LeKaitoW/rdo-game5#70]
Модель:

``` erlang
enum Место_дырки {СПРАВА, СЛЕВА, СВЕРХУ, СНИЗУ, ДЫРКИ_РЯДОМ_НЕТ}

type Фишки {
	int номер;
	int место;
}

type Дырка {
	int место;
}

resource фишка1 = Фишки.create(1, 1)
resource фишка2 = Фишки.create(2, 6)
resource фишка3 = Фишки.create(3, 4)
resource фишка4 = Фишки.create(4, 2)
resource фишка5 = Фишки.create(5, 5)
resource дырка = Дырка.create(3)

rule Перемещение_фишки (Место_дырки куда_перемещать, int на_сколько_перемещать) {
	relevant _фишка = Фишки.accessible.filter[где_дырка(место) == куда_перемещать].any();
	relevant _дырка = дырка;

	def execute() {
		_фишка.место = _фишка.место + на_сколько_перемещать;
		_дырка.место = _дырка.место - на_сколько_перемещать;
	}
}

constant длина_поля = 3;

int ряд(int место) {
	return (место - 1 ) / длина_поля + 1
}

int столбец(int место) {
	return (место - 1) % длина_поля + 1
}

Место_дырки где_дырка(int место) {
	if (столбец(место) == столбец(дырка.место) && ряд(место) == ряд(дырка.место) + 1)
		return Место_дырки.СВЕРХУ

	if (столбец(место) == столбец(дырка.место) && ряд(место) == ряд(дырка.место) - 1)
		return Место_дырки.СНИЗУ

	if (ряд(место) == ряд(дырка.место) && столбец(место) == столбец(дырка.место) - 1)
		return Место_дырки.СПРАВА

	if (ряд(место) == ряд(дырка.место) && столбец(место) == столбец(дырка.место) + 1)
		return Место_дырки.СЛЕВА

	return Место_дырки.ДЫРКИ_РЯДОМ_НЕТ
}

int Номер_фишки_на_месте(int место) {
	if (место == фишка1.место) {
		return 1
	} else if (место == фишка2.место) {
		return 2
	} else if (место == фишка3.место) {
		return 3
	} else if (место == фишка4.место) {
		return 4
	} else if (место == фишка5.место) {
		return 5
	}
	return 0
}

int eur() {
	var	ответ = 0
	ответ += Math.abs(Номер_фишки_на_месте(1) + Номер_фишки_на_месте(2) + Номер_фишки_на_месте(3) - 6)
	ответ += Math.abs(Номер_фишки_на_месте(4) + Номер_фишки_на_месте(5) + Номер_фишки_на_месте(6) - 9)
	return ответ
}

search Расстановка_фишек {
	edge перемещение_вправо = new Edge(Перемещение_фишки.create(Место_дырки.СПРАВА, 1), 1)
	edge перемещение_влево = new Edge(Перемещение_фишки.create(Место_дырки.СЛЕВА, -1), 1)
	edge перемещение_вверх = new Edge(Перемещение_фишки.create(Место_дырки.СВЕРХУ, -длина_поля), 1)
	edge перемещение_вниз = new Edge(Перемещение_фишки.create(Место_дырки.СНИЗУ, длина_поля), 1)

	def init() {
		startCondition = [Фишки.accessible.exists[номер != место]]
		terminateCondition = [Фишки.accessible.forall[номер == место]]
		heuristic = [eur() as double]
		compareTops = true
	}
}
```

При отображении графа происходит следующее:
![Screenshot2](http://cs627622.vk.me/v627622462/1f02b/d3ceHRmAV8E.jpg)
Т.е. в информационном окне написано, что всего в графе 241 вершина, но при этом на изображении графа есть вершины с номерами выше 241.
UPD: Всего в графе фактически 251 вершина.

**Comment by aurusov** [comment]
@bogachev-pa 
Смена родителя ?

**Comment by aurusov** [comment]
> но при этом на изображении графа есть вершины с номерами выше 241.

Пойму, если откажете и не буду припоминать на экзамене :) но всё равно прошу подсчитать фактическое кол-во вершин в графе.

**Comment by IChesnokov5** [comment]
Подсчитал. Всего в графе фактически 251 вершина, включая начальную.

**Comment by aurusov** [comment]
Видимо, 10 осталось в списке `Open`, а 241 в списке `Closed`.

**Comment by IChesnokov5** [comment]
На сколько я помню, в Nodes total должно быть количество вершин из обоих списков, а в Nodes opened количество открытых вершин.

> Т.е. в информационном окне написано, что открыта 241 вершина

Прошу прощения, только сейчас заметил, что неправильно написал. Естественно, там написано что всего в графе 241 вершина и при этом открыто 196 вершин. На деле получается, что всего в графе 251 вершина.

**Comment by bogachev-pa** [comment]
В коде имеем 3 величины:
`totalAdded` - инкрементируем каждый раз, когда добавляем вершину в граф, при этом, если такая вершина уже была в графе, то
а) если она лучше и производим смену родителя, инкрементируем
б) если она хуже, не инкрементируем
`totalOpened` - инкрементируем каждый раз, когда порождаем потомков вершины
`totalSpawned` - инкрементируем для каждого порожденного потомка, даже если он был отброшен (см, `totalAdded`, б))

Кажется, что все логично. Но при этом число `Nodes total`, которое выводится в граф считывается из `nodesOpen.size() + nodesClosed.size()`, а не из переменной `totalAdded` - думаю, здесь ошибка. Выводим не то число. Отличаются они на число добавленных, но не раскрытых вершин.

**Comment by aurusov** [comment]
Спасибо, переводим таску в багу.

**Comment by aurusov** [comment]
@bogachev-pa @k-alexandrovsky
Повторил ошибку. Странная ситуация. Ну ok, пусть `totalAdded` - это кол-во добавленных, `251`. И пусть оно может быть больше суммы `nodesOpen.size() + nodesClosed.size()` == `241`. Для этого есть объяснение. Но как объяснить, что _визуально_ на графе 251 вершина, а не 241 ? Ведь любая вершина может быть только в одном из этих списков.

**Comment by k-alexandrovsky** [comment]
Точно не смена родителя, потому что такое бывает раз в сто лет, насколько я помню. И точно не 10 раз за прогон.

Поиск переписывался несколько раз, плюс я уже все забыл, но мб в этом проблема:

> totalAdded - инкрементируем каждый раз, когда добавляем вершину в граф, при этом, если такая вершина уже была в графе, то
> а) если она лучше и производим смену родителя, инкрементируем
> б) если она хуже, не инкрементируем
> totalOpened - инкрементируем каждый раз, когда порождаем потомков вершины
> totalSpawned - инкрементируем для каждого порожденного потомка, даже если он был отброшен (см, totalAdded, б))

Мб при парсинге трассировки во время создания графа в ход идут эти мусорные вершины?

**Comment by bogachev-pa** [comment]
UPD: перечитал таску, ответ неактуален

**Comment by bogachev-pa** [comment]
Похоже, что дело действительно в смене родителя. Алгоритм поиска все делает правильно, однако отрисовщик [не учитывает смен родителя](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.ui/src/ru/bmstu/rk9/rao/ui/graph/TreeBuilder.java#L118) (`case NEW` и `case BETTER` обрабатываются одинаково).
В итоге при отрисовке у нас на графе остаются лишние вершины - те, у кого сменился родитель, из графа отрисовщика не удаляются.

**Comment by aurusov** [comment]
Да, на графе 251 вершина. Посмотрю что там с better.

**Comment by aurusov** [comment]
Чем больше разбираюсь в коде поиска, тем больше не понимаю, как это вообще работает.
1. @k-alexandrovsky Кирилл, вопрос по твоему коду 2014-года. [Удаление](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.lib/src/ru/bmstu/rk9/rao/lib/dpt/Search.java#L226) более дорогой вершины есть. Но почему потомки этой вершины не переключаются на новую ? Это не нужно ? Так и задумано, это где-то происходит дальше ?
2. ~~@k-alexandrovsky Кмк, удаление из (1) тоже неправильное. Надо же удалять из `nodesOpen` или `nodesClosed`, а не `nodesList`. Разве нет ?~~ Работает правильно.
3. @bogachev-pa Паша, блейм сдал тебя. Как трассировщик или граф узнают, какая вершина была удалена, если эта информация не [сериализуется](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.lib/src/ru/bmstu/rk9/rao/lib/dpt/Search.java#L242) ?

**Comment by bogachev-pa** [comment]
1_._ Бегло посмотрел, кажется действительно неправильным. По идее всем потомкам вершины надо заменить родителя на нового? Пока не уверен, мб что-то упускаю.
3_._ Сериализация делалась по образцу трассировки старого рдо, там эта информация не сохранялась. Если теперь она кажется нужной, давайте добавим.

**Comment by aurusov** [comment]
Анализ смен родителя из примера

```
25 -> 45 better than 39 -> 41
45 -> 46 better than 34 -> 39
46 -> 47 better than 39 -> 40
47 -> 48 better than 40 -> 42
12 -> 61 better than 31 -> 36
68 -> 79 better than 54 -> 65
79 -> 80 better than 65 -> 77
124 -> 152 better than 118 -> 150
129 -> 179 better than 139 -> 140
179 -> 180 better than 140 -> 158
```

```
25 -> 41 better than 39
12 -> 36 better than 31
63 -> 60 better than 50
56 -> 106 better than 90
111 -> 122 better than 121
141 -> 188 better than 134
```

**Comment by aurusov** [comment]
1. А для замены родителя у потомков надо менять модель данных [GraphNode ](https://github.com/aurusov/raox/blob/release/current/ru.bmstu.rk9.rao.lib/src/ru/bmstu/rk9/rao/lib/dpt/Search.java#L92), чтобы линейно не багать по графу в этом месте.

**Comment by aurusov** [comment]
1. Еще нужно обновить стоимость всех потомков более дорогой вершины

**Comment by aurusov** [comment]
Граф вообще не готов к удалению.
- Вся работа с моделью данных идет через индекс, в надежде, что индекс == номеру вершины. Если удалить вершину, то все летит нахер. Как мило.
- В gui графа пробрасывается только добавление вершин. Удаление же не может быть. Ура-ура-ура.
- Пока не понял, как переназначить предка потомкам. Класс `mxGraph` выглядит трешово.

Светит рефакторинг модели данных графа, её взаимодействия с гуи и возможный затык в библиотечном классе гуи при перестроении графа. Мило.
