### ISSUE TITLE
Добавить на граф состояние поля

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/rdo-game5#8]
По клику на вершину графа хочется видеть состояние поля, как в старых пятнашках, т.е. поле с фишками и описанием вершины.

**Comment by LeKaitoW** [comment]
Пример:
![screenshot from 2015-09-10 12 02 01](https://cloud.githubusercontent.com/assets/10632455/9792285/175f0e7c-57e8-11e5-983c-afffb06c6604.png)

Необходимо:
- увеличить шрифт цифр
- возможно как-то по-другому назначать координаты поля

**Comment by LeKaitoW** [comment]
UPD. 
![screenshot from 2015-09-28 15 59 47](https://cloud.githubusercontent.com/assets/10632455/10135889/03b9022c-65fa-11e5-9331-6756d5c30969.png)

**Comment by aurusov** [comment]
круть

**Comment by LeKaitoW** [comment]
Вопрос - двоеточие у `Board` стоит убрать для однообразия с окошком?

**Comment by aurusov** [comment]
да
